### PR TITLE
jshint config

### PR DESCRIPTION
**Pull request by ngodfraind**

### CODE REVIEW

**Comment by ngodfraind** [comment]
@stefk 

We should discuss this if you want to enforce coding style.
The "indent" option doesn't seem to work.

**Comment by stefk** [comment]
@ngodfraind. [eslint](http://eslint.org/) is a much more powerful alternative to jshint now. And as discussed previously, we could use [standard](http://standardjs.com/) (based on eslint) to avoid maintaining our own coding conventions. If we go that route, no linter config is necessary (and maybe the whole *app/dev/config* should be deleted or moved to claroline/Distribution).

cc @claroline/commiters

**Comment by ngodfraind** [comment]
https://github.com/claroline/git-hooks
This is very confusing then because we recommand jshint here.

**Comment by stefk** [comment]
I know... The decision to switch to standardjs was almost made when we met at Villard, but I don't know if we cannot apply it now without confirmation.

**Comment by ngodfraind** [comment]
It looks like that we can remove most files located in app/dev since it's handled by the dev bundle or outdated to avoid confusion.

**Comment by stefk** [comment]
Yep the whole directory can be deleted IMO.

**Pull request closed without merging**
