### PR TITLE
Cancel subscription

### PR DESCRIPTION
**Pull request by firepolo**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | ???
| Fixed issues | 

Allow to cancel subscriptions to a session.

Display cancellations list in participants view in session.
image

Replace unregister action by cancel action.
image

### CODE REVIEW

**Review by Elorfin — CHANGES_REQUESTED** [review]
- Creating a new entity for this is clearly overkill, a flag on the original registration is enough.
- This feature must use an option and be disabled by default.

**Comment by firepolo** [comment]
> 
> 
>     * Creating a new entity for this is clearly overkill, a flag on the original registration is enough.
>
We create a entity for keep the cancellation log not for change a "status". We want keep each cancellation and never recover.

**Comment by Elorfin** [comment]
A new entity also means, new Serializer, Finder, API endpoints and associated custom logic. This is too much complexity for an option inside a plugin. There are uncountable options in Claroline, we must keep complexity as low as possible.

Other "soft delete" features in Claroline use a flag on the original.

> We want keep each cancellation and never recover.

You need to add a recover action to manage user mistakes.

**Comment by Elorfin** [comment]
Closed due to inactivity.
The requested changes require a different approach, so this is useless to keep the current code.

**Comment by maieutiquer** [comment]
Those changes are crucial for our client and we're required to keep them unless we come up with a better solution, so for now we'll need to have them in a fork, which is not ideal for such big changes

**Pull request closed without merging**
