### PR TITLE
Change display format of duration

### PR DESCRIPTION
**Pull request by firepolo**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | ???
| Fixed issues | format of course duration

Change the format of display of course duration

### CODE REVIEW

**Comment by Elorfin** [comment]
Why is this needed ?

**Comment by firepolo** [comment]
For display course duration in days only.  "1.5 days" instead of "1 day 12 hours".

**Comment by Elorfin** [comment]
We will need to find another way to solve this.
Those who create sessions with a duration in months will also get the display in days.

This need more thinking. IMHO, we should update (or create a new) formatter in the core. The current formatter is far from perfect anyway.

**Comment by firepolo** [comment]
Maybe to have a new field for "duration type" -> "month, days, hours" ?
or format the duration depending on the nearest of number of seconds "years > month > days > hours > ...".

**Pull request closed without merging**
