### PR TITLE
log async:

### PR DESCRIPTION
**Pull request by Zowac**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Fixed issues | comma-separated list of issues fixed by the PR, if any

Make log creation asynchronous

### CODE REVIEW

**Comment by Zowac** [comment]
@Elorfin && @chalasr 

Hi, I think I made all the changes (move the creations of logs in messenger), can you make a review please :)

**Comment by Elorfin** [comment]
IMO, we shouldn't move all existing events in the messenger.

Why not just send a CreateLog message here  https://github.com/claroline/Claroline/blob/13.x/src/main/log/Subscriber/SecurityLogSubscriber.php#L55 and here https://github.com/claroline/Claroline/blob/13.x/src/main/log/Subscriber/FunctionalLogSubscriber.php#L37 ?

**Comment by Zowac** [comment]
I thought about it too, but from my point of view, it seemed a bit strange to dispatch an event and then only dispatch a message

**Comment by Elorfin** [comment]
We can not use this approach because : 
- As we will log more things, we will need to move all the events in the messenger.
- Some of the events are used to generate the `Response`, so we can not do it asynchronously.

Replaced by : https://github.com/claroline/Claroline/pull/1767.

**Pull request closed without merging**
